services:
  postgres:
    image: postgres:18
    container_name: bookface_db
    environment:
      POSTGRES_DB: bookface
      POSTGRES_USER: Josip
      POSTGRES_PASSWORD: Pa55w.rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Josip -d bookface_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
